jonaharagon:
  name: Jonah
  description: Team Member
  avatar: https://github.com/jonaharagon.png
freddy-m:
  name: Freddy
  description: Team Member
  avatar: https://github.com/freddy-m.png
dngray:
  name: Daniel
  description: Team Member
  avatar: https://github.com/dngray.png
danarel:
  name: Dan Arel
  description: Guest Contributor
  avatar: https://github.com/danarel.png
